version: '3'

services:
  app:
    image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./play-scala-seed:/root
      - sbt:/root/.ivy2
      - sbt:/root/.sbt
    ports:
      - "9000:9000"
    command: sbt run
    tty: true

volumes:
  sbt: