version: '3'

services:
  app:
    image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    environment:
      TZ: Asia/Tokyo
    volumes:
      - sbt:/root/.ivy2
      - sbt:/root/.sbt
      - ./scala-seed-project:/root
    ports:
      - "9000:9000"
    command: sbt run

volumes:
  sbt: